### ISSUE TITLE
pass maps instead of positional arguments

### ISSUE THREAD

**Issue by kliph** [kliph/sunrise#1]

**Comment by ryanhinkel** [comment]
I'm not sure I understand this issue.

**Comment by kliph** [comment]
For example, the `mountain-path` function accepts 5 arguments, https://github.com/kliph/sunrise/blob/master/src/sunrise/component.cljs#L23 .  These arguments are just `props`, so it would be better if we accepted a single map, something like

```
(defn mountain-path [{:keys [n width height base nth-mountain] :as props}]
  ...
```

There are several places in the codebase where we're passing props like this.
